## Немного о операции `print`

In [1]:
name = "Eric"
profession = "comedian"
affiliation = "Monty Python"


message = f"Hi {name}. You are a {profession}. You were in {affiliation}. "
 
print(message)

Hi Eric. You are a comedian. You were in Monty Python. 


In [2]:
name = "Eric"
profession = "comedian"
affiliation = "Monty Python"


message = f"Hi {name}. " \
          f"You are a {profession}. " \
          f"You were in {affiliation}. "
 
print(message)

Hi Eric. You are a comedian. You were in Monty Python. 


In [3]:
name = "Eric"
profession = "comedian"
affiliation = "Monty Python"


message = f"Hi {name}. \n" \
          f"You are a {profession}. \n" \
          f"You were in {affiliation}."
 
print(message)

Hi Eric. 
You are a comedian. 
You were in Monty Python.


In [4]:
name = "Eric"
profession = "comedian"
affiliation = "Monty Python"


message = f"""
    Hi {name}. 
    You are a {profession}. 
    You were in {affiliation}.
""" 
print(message)


    Hi Eric. 
    You are a comedian. 
    You were in Monty Python.



In [6]:
from num2words import num2words
num2words(42, lang = 'ru')

'сорок два'

In [7]:
a = num2words(10, lang = 'ru').capitalize()
print(f'{a} бутылок пива в баре!')

Десять бутылок пива в баре!


# Введение в NumPy

NumPy предназначен для:
1. быстрых операций с векторами операции массивов для обработки и очистки данных
2. эффективной сортировки, поиска уникальных элементов и присвоения значений
3. получения описательной статистики
4. проверки согласованности данных, обработки и объединения данных
5. выражения условной логики, вместо циклов с ветвями if-elif-else
6. групповых манипуляций с данными (агрегация, трансформация, применение функций)

In [8]:
[1,2,3,4] + [1,2,3,4]

[1, 2, 3, 4, 1, 2, 3, 4]

Как корректно загружать библиотеку?

In [9]:
import numpy as np
from IPython.display import display

In [10]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [11]:
%time for _ in range(50): my_arr_2 = my_arr * 2

CPU times: user 82.5 ms, sys: 39 ms, total: 121 ms
Wall time: 119 ms


In [12]:
%time for _ in range(50): my_list_2 = [x *2 for x in my_list]

CPU times: user 4.06 s, sys: 944 ms, total: 5 s
Wall time: 5.02 s


## "Случайное зерно"
Зачем нужно фиксировать "случайное зерно"?

In [14]:
np.random.seed(42) 
###
'''
почему так любят число 42 в программировании:
Самый Главный Вопрос Жизни, Вселенной и Вообще 
https://www.youtube.com/watch?v=D5O0vqatpXg
'''
###
data = np.random.randn(2,3)
data

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696]])

### Наконец-то у нас есть "нормальные" оперрации с векторами и матрицами

In [15]:
data * 10

array([[ 4.96714153, -1.38264301,  6.47688538],
       [15.23029856, -2.34153375, -2.34136957]])

In [16]:
data + data

array([[ 0.99342831, -0.2765286 ,  1.29537708],
       [ 3.04605971, -0.46830675, -0.46827391]])

In [17]:
data.shape

(2, 3)

In [18]:
data.dtype

dtype('float64')

### Переходим от списка к матрице (массиву) - `array`

In [25]:
data_1 = [6, 7.5, 8, 10, 0, 1]
arr_1 = np.array(data_1)
arr_1

array([ 6. ,  7.5,  8. , 10. ,  0. ,  1. ])

In [26]:
data_2 = [[ 1, 2, 3, 4],[ 5, 6, 7, 8]]
arr_2 = np.array(data_2)
arr_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
arr_2.ndim

2

In [28]:
arr_2.shape

(2, 4)

In [29]:
arr_1.dtype

dtype('float64')

In [30]:
arr_2.dtype

dtype('int64')

### Разные нулевые массивы

In [48]:
zer = np.zeros([2,5])
emp = np.empty([2,5]) #не рекомендую ...
display(zer)
display(emp)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Разные полезные команды

In [49]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [50]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [51]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
data_3 = [[ 1, 2, 3],[ 4, 5, 6],[ 7, 8, 9]]
np.ones_like(data_3)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### Преобразование типов данных внутри NumPy

In [54]:
arr_1 = np.array([1, 2, 3], dtype=np.float64)
arr_1

array([1., 2., 3.])

In [55]:
arr_1.dtype

dtype('float64')

In [56]:
arr_2 = np.array([1, 2, 3], dtype=np.int32)
arr_2

array([1, 2, 3], dtype=int32)

In [57]:
arr_2.dtype

dtype('int32')

In [58]:
arr_3 = np.array([ 1, 2, 3, 4, 5])
arr_3.dtype

dtype('int64')

In [59]:
arr_4 = arr_3.astype(np.float64)
arr_4.dtype

dtype('float64')

In [60]:
arr_5 = np.array([ 3.6, 4, -5.8, 10.2, 18.5, -2.5, 0.3])
arr_5

array([ 3.6,  4. , -5.8, 10.2, 18.5, -2.5,  0.3])

In [61]:
arr_5.astype(np.int32)

array([ 3,  4, -5, 10, 18, -2,  0], dtype=int32)

In [62]:
arr_6 = np.array(['1.25', '18', '-3.2', '42.1'], )
arr_7 = arr_6.astype(float)
arr_7

array([ 1.25, 18.  , -3.2 , 42.1 ])

In [63]:
arr_7.dtype

dtype('float64')

### Преобразование по образцу

In [64]:
int_array = np.arange(10)
display(int_array)
calibre = np.array([0.22, 0.23, -0.45])

int_array.astype(calibre.dtype)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Базовые типы данных в NumPy:
https://numpy.org/devdocs/user/basics.types.html

# Работа с матрицами

### Сравнение

In [65]:
arr = np.array([[0,2,3],[4,5,6]])
arr

array([[0, 2, 3],
       [4, 5, 6]])

In [66]:
arr2 = np.array([[0., 12., 3.],[ 2., 5., -2.]])
arr2

array([[ 0., 12.,  3.],
       [ 2.,  5., -2.]])

In [67]:
arr > arr2

array([[False, False, False],
       [ True, False,  True]])

In [68]:
0 == 0.

True

### Срезы

In [69]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
arr[5]

5

In [71]:
arr[5:8]

array([5, 6, 7])

In [72]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [73]:
### Внимание! Вспоминаем про ссылки на списки
arr_slice = arr[5:8]
display(arr_slice)
arr_slice[1] = 123456

display(arr)

array([12, 12, 12])

array([     0,      1,      2,      3,      4,     12, 123456,     12,
            8,      9])

In [74]:
arr2d = np.array([[ 1, 2, 3], [ 4, 5, 6], [ 7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [75]:
arr2d[0][2]

3

In [76]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [77]:
arr2d[1,:2]

array([4, 5])

In [78]:
arr2d[:2,2]

array([3, 6])

In [79]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [80]:
arr2d[:2,1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Особенность размерности

In [81]:
# матрица
display(arr2d[:2,1:])
arr2d[:2,1:].shape

array([[0, 0],
       [0, 0]])

(2, 2)

In [82]:
# вектор
display(arr2d[2])
arr2d[2].shape

array([7, 8, 9])

(3,)

In [83]:
# ?
display(arr2d[2,:])
arr2d[2,:].shape

array([7, 8, 9])

(3,)

In [84]:
# ?
display(arr2d)
display(arr2d[2:,:])
arr2d[2:,:].shape

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

array([[7, 8, 9]])

(1, 3)

In [85]:
# ?
display(arr2d[:,:1])
arr2d[:,:1].shape

array([[1],
       [4],
       [7]])

(3, 1)

In [86]:
# ?
display(arr2d[1,2])
arr2d[1, 2].shape

0

()