In [1]:
import numpy as np
from IPython.display import display

# Срезы по условию

In [2]:
np.random.seed(42) 
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819],
       [-0.54438272,  0.11092259, -1.15099358,  0.37569802]])

In [3]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [4]:
data[names == 'Bob']

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753]])

In [5]:
data[names == 'Bob', 2:]

array([[ 0.64768854,  1.52302986],
       [-1.72491783, -0.56228753]])

In [6]:
data[names == 'Bob', 3]

array([ 1.52302986, -0.56228753])

In [7]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [8]:
data[names != 'Bob']

array([[-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819],
       [-0.54438272,  0.11092259, -1.15099358,  0.37569802]])

In [9]:
data[ ~(names == 'Bob') ]

array([[-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819],
       [-0.54438272,  0.11092259, -1.15099358,  0.37569802]])

In [10]:
mask = names == 'Bob'
data[~mask]

array([[-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819],
       [-0.54438272,  0.11092259, -1.15099358,  0.37569802]])

In [11]:
mask = (names == 'Bob')|(names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [12]:
data[mask]

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ]])

In [13]:
data[data < 0] = 0
data

array([[0.49671415, 0.        , 0.64768854, 1.52302986],
       [0.        , 0.        , 1.57921282, 0.76743473],
       [0.        , 0.54256004, 0.        , 0.        ],
       [0.24196227, 0.        , 0.        , 0.        ],
       [0.        , 0.31424733, 0.        , 0.        ],
       [1.46564877, 0.        , 0.0675282 , 0.        ],
       [0.        , 0.11092259, 0.        , 0.37569802]])

In [14]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 1.57921282, 0.76743473],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.46564877, 0.        , 0.0675282 , 0.        ],
       [0.        , 0.11092259, 0.        , 0.37569802]])

### Работа с индексами

In [15]:
arr = np.zeros((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [16]:
arr[[ 4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [17]:
arr[[ -3, -1, -6]]

array([[5., 5., 5., 5.],
       [7., 7., 7., 7.],
       [2., 2., 2., 2.]])

In [18]:
arr = np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [19]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [20]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### Транспонирование

In [21]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [23]:
np.dot(arr,arr.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

### Быстрые функции NumPy

In [24]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [26]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [27]:
np.random.seed(42)
x = np.random.randn(8)
y = np.random.randn(8)
display(x)
display(y)
np.maximum(x, y)

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473])

array([-0.46947439,  0.54256004, -0.46341769, -0.46572975,  0.24196227,
       -1.91328024, -1.72491783, -0.56228753])

array([ 0.49671415,  0.54256004,  0.64768854,  1.52302986,  0.24196227,
       -0.23413696,  1.57921282,  0.76743473])

Математические функции NumPy:<br>
https://numpy.org/doc/stable/reference/routines.math.html

## Опереции с условиями в матрицах

In [28]:
np.random.seed(42)
arr = np.random.randn(4, 4)
arr

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753]])

In [29]:
arr > 0

array([[ True, False,  True,  True],
       [False, False,  True,  True],
       [False,  True, False, False],
       [ True, False, False, False]])

In [30]:
np.where(arr > 0, 2, -2)

array([[ 2, -2,  2,  2],
       [-2, -2,  2,  2],
       [-2,  2, -2, -2],
       [ 2, -2, -2, -2]])

In [31]:
np.where(arr > 0, 2, arr)

array([[ 2.        , -0.1382643 ,  2.        ,  2.        ],
       [-0.23415337, -0.23413696,  2.        ,  2.        ],
       [-0.46947439,  2.        , -0.46341769, -0.46572975],
       [ 2.        , -1.91328024, -1.72491783, -0.56228753]])

## Статистистики

In [32]:
np.random.seed(42)
arr = np.random.randn(5, 4)
arr

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ]])

In [33]:
arr.mean()

-0.17129856144182892

In [34]:
np.mean(arr)

-0.17129856144182892

In [35]:
arr.sum()

-3.4259712288365787

### Разберемся с осями

In [36]:
arr = np.arange(12).reshape(4,3)
arr 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
arr.sum(axis=1)

array([ 3, 12, 21, 30])

In [38]:
arr.sum()

66

In [39]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [40]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [42]:
arr.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

## Булевы операции для работы с массивами

In [43]:
np.random.seed(42)
arr = np.random.randn(100)
(arr > 0).sum()

46

## Сортировка

In [44]:
np.random.seed(42)
arr = np.random.randn(6)
arr

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696])

In [45]:
arr.sort()
arr

array([-0.23415337, -0.23413696, -0.1382643 ,  0.49671415,  0.64768854,
        1.52302986])

In [46]:
np.random.seed(42)
arr = np.random.randn(5, 3)
arr

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439],
       [ 0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783]])

In [47]:
arr.sort( axis = 0)
arr

array([[ 0.24196227, -1.91328024, -1.72491783],
       [ 0.49671415, -0.46341769, -0.46947439],
       [ 0.54256004, -0.23415337, -0.46572975],
       [ 1.52302986, -0.1382643 , -0.23413696],
       [ 1.57921282,  0.76743473,  0.64768854]])

In [48]:
# почему нельзя оставить коментарий закрытым?
#np.random.seed(42) 
#arr = np.random.randn(5, 3)
arr.sort( axis = 1)
arr

array([[-1.91328024, -1.72491783,  0.24196227],
       [-0.46947439, -0.46341769,  0.49671415],
       [-0.46572975, -0.23415337,  0.54256004],
       [-0.23413696, -0.1382643 ,  1.52302986],
       [ 0.64768854,  0.76743473,  1.57921282]])

### С помощью сортировки найти 5% перцентиль

In [49]:
np.random.seed(42)
large_arr = np.random.randn(1000)
large_arr.sort()
display(int(0.05 * len(large_arr)))
large_arr[int(0.05 * len(large_arr))] # 5%–ный перцентиль

50

-1.5255251709247388

## Дубликаты в данных

In [50]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [51]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [52]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [53]:
np.union1d([1,2,3,4], [3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [54]:
np.intersect1d([1,2,3,4], [3,4,5,6])

array([3, 4])

# Расширим знания о функциях

In [55]:
def f(x,y,z):
    return (x+y)/z
a = 5
b = 6
c = 7.5

result = f(a,b,c)
result 

1.4666666666666666

In [56]:
def my_func(x, y, z=2):
    if z>1:
        return z*(x+y)
    else:
        return z/(x+y)

In [57]:
my_func(5,6)

22

In [58]:
my_func(5,6,1)

0.09090909090909091

In [59]:
my_func(x = 5, y = 6, z = 0.1)

0.009090909090909092

In [60]:
def f():
    a = 4
    b = 10
    c = 25
    return a, b, c

u, v, g = f()
print(u, v, g)

4 10 25
