# Введение в NumPy

NumPy предназначен для:
1. быстрых операций с векторами операции массивов для обработки и очистки данных
2. эффективной сортировки, поиска уникальных элементов и присвоения значений
3. получения описательной статистики
4. проверки согласованности данных, обработки и объединения данных
5. выражения условной логики, вместо циклов с ветвями if-elif-else
6. групповых манипуляций с данными (агрегация, трансформация, применение функций)

In [1]:
import numpy as np
from IPython.display import display

In [2]:
my_arr =    np.array(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(50): my_arr_2 = my_arr * 2

CPU times: user 63 µs, sys: 3 µs, total: 66 µs
Wall time: 68.2 µs


In [4]:
%time for _ in range(50): my_list_2 = [x *2 for x in my_list]

CPU times: user 2.59 s, sys: 628 ms, total: 3.22 s
Wall time: 3.22 s


In [5]:
np.random.seed(42) 
###
'''
почему так любят число 42 в программировании:
Самый Главный Вопрос Жизни, Вселенной и Вообще 
https://www.youtube.com/watch?v=D5O0vqatpXg
'''
###
data = np.random.randn(2,3)
data

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696]])

### Наконец-то у нас есть "нормальные" оперрации с векторами и матрицами

In [6]:
data * 10

array([[ 4.96714153, -1.38264301,  6.47688538],
       [15.23029856, -2.34153375, -2.34136957]])

In [7]:
data + data

array([[ 0.99342831, -0.2765286 ,  1.29537708],
       [ 3.04605971, -0.46830675, -0.46827391]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

### Переходим от списка к матрице (массиву)

In [10]:
data_1 = [6, 7.5, 8, 10, 0, 1]
arr_1 = np.array(data_1)
arr_1

array([ 6. ,  7.5,  8. , 10. ,  0. ,  1. ])

In [11]:
data_2 = [[ 1, 2, 3, 4],[ 5, 6, 7, 8]]
arr_2 = np.array(data_2)
arr_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr_2.ndim

2

In [13]:
arr_2.shape

(2, 4)

In [14]:
arr_1.dtype

dtype('float64')

In [15]:
arr_2.dtype

dtype('int64')

### Разные нулевые массивы

In [8]:
zer = np.zeros(10)
emp = np.empty(10)
zer

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
emp

array([0.00000000e+000, 0.00000000e+000, 1.77229088e-310, 3.50977866e+064,
       0.00000000e+000, 0.00000000e+000,             nan,             nan,
       3.50977942e+064, 6.93026480e-310])

In [18]:
zer == emp

array([False, False, False,  True,  True, False, False, False, False,
       False])

### Разные полезные команды

In [19]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
data_3 = [[ 1, 2, 3],[ 4, 5, 6],[ 7, 8, 9]]
np.ones_like(data_3)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### Преобразование типов данных внутри NumPy

In [24]:
arr_1 = np.array([1, 2, 3], dtype=np.float64)
arr_1

array([1., 2., 3.])

In [25]:
arr_1.dtype

dtype('float64')

In [26]:
arr_2 = np.array([1, 2, 3], dtype=np.int32)
arr_2

array([1, 2, 3], dtype=int32)

In [27]:
arr_2.dtype

dtype('int32')

In [28]:
arr_3 = np.array([ 1, 2, 3, 4, 5])
arr_3.dtype

dtype('int64')

In [29]:
arr_4 = arr_3.astype(np.float64)
arr_4.dtype

dtype('float64')

In [30]:
arr_5 = np.array([ 3.6, 4, -5.8, 10.2, 18.5, -2.5, 0.3])
arr_5

array([ 3.6,  4. , -5.8, 10.2, 18.5, -2.5,  0.3])

In [31]:
arr_5.astype(np.int32)

array([ 3,  4, -5, 10, 18, -2,  0], dtype=int32)

In [32]:
arr_6 = np.array(['1.25', '18', '-3.2', '42.1'], )
arr_7 = arr_6.astype(float)
arr_7

array([ 1.25, 18.  , -3.2 , 42.1 ])

In [33]:
arr_7.dtype

dtype('float64')

### Преобразование по образцу

In [34]:
int_array = np.arange(10)
calibre = np.array([0.22, 0.23, -0.45])

int_array.astype(calibre.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Базовые типы данных в NumPy:
https://numpy.org/devdocs/user/basics.types.html

# Работа с матрицами

### Сравнение

In [35]:
arr = np.array([[1,2,3],[4,5,6]], dtype=np.float64)
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [36]:
arr2 = np.array([[0., 12., 3.],[ 2., 5., -2.]])
arr2

array([[ 0., 12.,  3.],
       [ 2.,  5., -2.]])

In [37]:
arr > arr2

array([[ True, False, False],
       [ True, False,  True]])

### Срезы

In [38]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr[5]

5

In [40]:
arr[5:8]

array([5, 6, 7])

In [41]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [42]:
### Внимание! Вспоминаем про ссылки на списки
arr_slice = arr[5:8]
display(arr_slice)
arr_slice[1] = 123456

display(arr)

array([12, 12, 12])

array([     0,      1,      2,      3,      4,     12, 123456,     12,
            8,      9])

In [43]:
arr2d = np.array([[ 1, 2, 3], [ 4, 5, 6], [ 7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [44]:
arr2d[0][2]

3

In [45]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [46]:
arr2d[1,:2]

array([4, 5])

In [47]:
arr2d[:2,2]

array([3, 6])

In [48]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [49]:
arr2d[:2,1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Особенность размерности

In [50]:
# матрица
display(arr2d[:2,1:])
arr2d[:2,1:].shape

array([[0, 0],
       [0, 0]])

(2, 2)

In [51]:
# вектор
display(arr2d[2])
arr2d[2].shape

array([7, 8, 9])

(3,)

In [52]:
# ?
display(arr2d[2,:])
arr2d[2,:].shape

array([7, 8, 9])

(3,)

In [53]:
# ?
display(arr2d[2:,:])
arr2d[2:,:].shape

array([[7, 8, 9]])

(1, 3)

In [54]:
# ?
display(arr2d[:,:2])
arr2d[:,:2].shape

array([[1, 0],
       [4, 0],
       [7, 8]])

(3, 2)

In [55]:
# ?
display(arr2d[1,:2])
arr2d[1,
      2].shape

array([4, 0])

(2,)

In [56]:
# ?
display(arr2d[1:2,:2])
arr2d[1:2,:2].shape

array([[4, 0]])

(1, 2)

### Срезы по условию

In [57]:
np.random.seed(42) 
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819],
       [-0.54438272,  0.11092259, -1.15099358,  0.37569802]])

In [58]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [59]:
data[names == 'Bob']

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753]])

In [60]:
data[names == 'Bob', 2:]

array([[ 0.64768854,  1.52302986],
       [-1.72491783, -0.56228753]])

In [61]:
data[names == 'Bob', 3]

array([ 1.52302986, -0.56228753])

In [62]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [63]:
data[names != 'Bob']

array([[-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819],
       [-0.54438272,  0.11092259, -1.15099358,  0.37569802]])

In [64]:
data[ ~(names == 'Bob') ]

array([[-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819],
       [-0.54438272,  0.11092259, -1.15099358,  0.37569802]])

In [65]:
mask = names == 'Bob'
data[~mask]

array([[-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819],
       [-0.54438272,  0.11092259, -1.15099358,  0.37569802]])

In [66]:
mask = (names == 'Bob')|(names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [67]:
data[mask]

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ]])

In [68]:
data[data < 0] = 0
data

array([[0.49671415, 0.        , 0.64768854, 1.52302986],
       [0.        , 0.        , 1.57921282, 0.76743473],
       [0.        , 0.54256004, 0.        , 0.        ],
       [0.24196227, 0.        , 0.        , 0.        ],
       [0.        , 0.31424733, 0.        , 0.        ],
       [1.46564877, 0.        , 0.0675282 , 0.        ],
       [0.        , 0.11092259, 0.        , 0.37569802]])

In [69]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 1.57921282, 0.76743473],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.46564877, 0.        , 0.0675282 , 0.        ],
       [0.        , 0.11092259, 0.        , 0.37569802]])

### Работа с индексами

In [70]:
arr = np.zeros((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [71]:
arr[[ 4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [72]:
arr[[ -3, -1, -6]]

array([[5., 5., 5., 5.],
       [7., 7., 7., 7.],
       [2., 2., 2., 2.]])

In [73]:
arr = np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [74]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [75]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### Транспонирование

In [76]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [77]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [78]:
np.dot(arr,arr.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

### Быстрые функции NumPy

In [79]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [81]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [82]:
np.random.seed(42)
x = np.random.randn(8)
y = np.random.randn(8)
display(x)
display(y)
np.maximum(x, y)

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473])

array([-0.46947439,  0.54256004, -0.46341769, -0.46572975,  0.24196227,
       -1.91328024, -1.72491783, -0.56228753])

array([ 0.49671415,  0.54256004,  0.64768854,  1.52302986,  0.24196227,
       -0.23413696,  1.57921282,  0.76743473])

Математические функции NumPy:<br>
https://numpy.org/doc/stable/reference/routines.math.html

## Опереции с условиями в матрицах

In [83]:
np.random.seed(42)
arr = np.random.randn(4, 4)
arr

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753]])

In [84]:
arr > 0

array([[ True, False,  True,  True],
       [False, False,  True,  True],
       [False,  True, False, False],
       [ True, False, False, False]])

In [85]:
np.where(arr > 0, 2, -2)

array([[ 2, -2,  2,  2],
       [-2, -2,  2,  2],
       [-2,  2, -2, -2],
       [ 2, -2, -2, -2]])

In [86]:
np.where(arr > 0, 2, arr)

array([[ 2.        , -0.1382643 ,  2.        ,  2.        ],
       [-0.23415337, -0.23413696,  2.        ,  2.        ],
       [-0.46947439,  2.        , -0.46341769, -0.46572975],
       [ 2.        , -1.91328024, -1.72491783, -0.56228753]])

## Статистистики

In [10]:
np.random.seed(42)
arr = np.random.randn(5, 4)
arr

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ]])

In [88]:
arr.mean()

-0.17129856144182892

In [89]:
np.mean(arr)

-0.17129856144182892

In [90]:
arr.sum()

-3.4259712288365787

### Разберемся с осями

In [11]:
arr

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ]])

In [91]:
arr.mean(axis=1)

array([ 0.63229206,  0.4695893 , -0.21401545, -0.98963083, -0.75472789])

In [92]:
arr.sum(axis=0)

array([-0.97778246, -1.42887413, -0.86945825, -0.1498564 ])

In [93]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [94]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [95]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [96]:
arr.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

## Булевы операции для работы с массивами

In [97]:
np.random.seed(42)
arr = np.random.randn(100)
(arr > 0).sum()

46

## Сортировка

In [98]:
np.random.seed(42)
arr = np.random.randn(6)
arr

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696])

In [99]:
arr.sort()
arr

array([-0.23415337, -0.23413696, -0.1382643 ,  0.49671415,  0.64768854,
        1.52302986])

In [12]:
np.random.seed(42)
arr = np.random.randn(5, 3)
arr

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439],
       [ 0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783]])

In [13]:
arr.sort( axis = 0)
arr

array([[ 0.24196227, -1.91328024, -1.72491783],
       [ 0.49671415, -0.46341769, -0.46947439],
       [ 0.54256004, -0.23415337, -0.46572975],
       [ 1.52302986, -0.1382643 , -0.23413696],
       [ 1.57921282,  0.76743473,  0.64768854]])

In [15]:
# почему нельзя оставить коментарий закрытым?
np.random.seed(42) 
arr = np.random.randn(5, 3)
arr.sort( axis = 1)
arr

array([[-0.1382643 ,  0.49671415,  0.64768854],
       [-0.23415337, -0.23413696,  1.52302986],
       [-0.46947439,  0.76743473,  1.57921282],
       [-0.46572975, -0.46341769,  0.54256004],
       [-1.91328024, -1.72491783,  0.24196227]])

### С помощью сортировки найти 5% перцентиль

In [103]:
np.random.seed(42)
large_arr = np.random.randn(1000)
large_arr.sort()
display(int(0.05 * len(large_arr)))
large_arr[int(0.05 * len(large_arr))] # 5%–ный перцентиль

50

-1.5255251709247388

## Дубликаты в данных

In [104]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [105]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [106]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [107]:
np.union1d([1,2,3,4], [3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [108]:
np.intersect1d([1,2,3,4], [3,4,5,6])

array([3, 4])

# Расширим знания о функциях

In [109]:
def f(x,y,z):
    return (x+y)/z
a = 5
b = 6
c = 7.5

result = f(a,b,c)
result 

1.4666666666666666

In [110]:
def my_func(x, y, z=2):
    if z>1:
        return z*(x+y)
    else:
        return z/(x+y)

In [111]:
my_func(5,6)

22

In [112]:
my_func(5,6,1)

0.09090909090909091

In [113]:
my_func(x = 5, y = 6, z = 0.1)

0.009090909090909092

In [114]:
def f():
    a = 4
    b = 10
    c = 25
    return a, b, c

u, v, g = f()
print(u, v, g)

4 10 25
